### ISSUE TITLE
figure out how to get height of react-native-tab-view

### ISSUE THREAD

**Issue by hsunami10** [hsunami10/LDR-App-client#25]
https://github.com/react-native-community/react-native-tab-view/issues/612

**Comment by gazoudoudou** [comment]
But there is no onLayout props.. How did you do ?

**Comment by hsunami10** [comment]
@gazoudoudou the only reason why I wanted the height of the tab view was to calculate the height of the internal view...so I just used onLayout on the views in renderScene. so not really a direct fix, but works in my case. I have not completely solved this issue yet
